import type { NetworkInfo } from "../extra.infos";

export const NETWORK_INFOS: NetworkInfo[] = [
	{
		runtimeChain: "Ethereum Mainnet",
		urn: "urn:ocn:ethereum:1",
		chainDecimals: [18],
		chainTokens: ["ETH"],
	},
	{
		runtimeChain: "Ethereum Sepolia (Testnet)",
		urn: "urn:ocn:ethereum:11155111",
		chainDecimals: [18],
		chainTokens: ["ETH"],
	},
	{
		runtimeChain: "Bitcoin",
		urn: "urn:ocn:bitcoin:0",
		icon: "bitcoin.svg",
	},
	{
		runtimeChain: "Bitcoin Cash",
		urn: "urn:ocn:bitcoin-cash:0",
		icon: "bitcoin-cash.svg",
	},
	{
		runtimeChain: "Bitcoin Gold",
		urn: "urn:ocn:bitcoin-gold:0",
		icon: "bitcoin-gold.png",
	},
	{ runtimeChain: "BSV", urn: "urn:ocn:bitcoin-sv:0", icon: "bsv.png" },
	{ runtimeChain: "Litecoin", urn: "urn:ocn:litecoin:0", icon: "litecoin.png" },
	{ runtimeChain: "Solana", urn: "urn:ocn:solana:0" },
	{ runtimeChain: "Monero", urn: "urn:ocn:monero:0", icon: "monero.png" },
	{ runtimeChain: "Dash", urn: "urn:ocn:dash:0", icon: "dash.png" },
	{ runtimeChain: "Zcash", urn: "urn:ocn:zcash:0", icon: "zcash.png" },
	{ runtimeChain: "Tron", urn: "urn:ocn:tron:0", icon: "tron.png" },
	{ runtimeChain: "Verge", urn: "urn:ocn:verge:0", icon: "verge.png" },
	{ runtimeChain: "Ripple", urn: "urn:ocn:ripple:0", icon: "ripple.png" },
	{ runtimeChain: "Sui", urn: "urn:ocn:sui:0x35834a8a" },
	{ runtimeChain: "Solana", urn: "urn:ocn:solana:101" },
	{ runtimeChain: "Celo", urn: "urn:ocn:ethereum:42220" },
	{ runtimeChain: "Base", urn: "urn:ocn:ethereum:8453" },
	{ runtimeChain: "Arbitrum", urn: "urn:ocn:ethereum:42161" },
	{ runtimeChain: "Optimism", urn: "urn:ocn:ethereum:10" },
	{ runtimeChain: "BNB Chain", urn: "urn:ocn:ethereum:56" },
	{ runtimeChain: "Polygon", urn: "urn:ocn:ethereum:137" },
	{ runtimeChain: "Avalanche", urn: "urn:ocn:ethereum:43114" },
	{ runtimeChain: "Fantom", urn: "urn:ocn:ethereum:250" },
	{ runtimeChain: "Harmony", urn: "urn:ocn:ethereum:1666600000" },
	{ runtimeChain: "Aptos", urn: "urn:ocn:aptos:1" },
	{
		runtimeChain: "Ethereum Classic",
		urn: "urn:ocn:ethereum-classic:61",
		icon: "ethereum-classic.webp",
	},
	{ runtimeChain: "Polkadot Relay", urn: "urn:ocn:polkadot:0" },
	{ runtimeChain: "Polkadot Asset Hub", urn: "urn:ocn:polkadot:1000" },
	{ runtimeChain: "Polkadot Bridge Hub", urn: "urn:ocn:polkadot:1002" },
	{ runtimeChain: "Polkadot People Chain", urn: "urn:ocn:polkadot:1005" },
	{ runtimeChain: "Polkadot Coretime", urn: "urn:ocn:polkadot:1005" },
	{ runtimeChain: "Acala", urn: "urn:ocn:polkadot:2000" },
	{ runtimeChain: "Moonbeam", urn: "urn:ocn:polkadot:2004" },
	{ runtimeChain: "Astar", urn: "urn:ocn:polkadot:2006" },
	{ runtimeChain: "Bifrost", urn: "urn:ocn:polkadot:2030" },
	{ runtimeChain: "Centrifuge", urn: "urn:ocn:polkadot:2031" },
	{ runtimeChain: "Interlay", urn: "urn:ocn:polkadot:2032" },
	{ runtimeChain: "Hydration", urn: "urn:ocn:polkadot:2034" },
	{ runtimeChain: "Hyperbridge", urn: "urn:ocn:polkadot:3367" },
	{ runtimeChain: "Mythos", urn: "urn:ocn:polkadot:3369" },
	{ runtimeChain: "Kusama Relay", urn: "urn:ocn:kusama:0" },
	{ runtimeChain: "Kusama Asset Hub", urn: "urn:ocn:kusama:1000" },
	{ runtimeChain: "Kusama Bridge Hub", urn: "urn:ocn:kusama:1002" },
	{ runtimeChain: "Kusama People Chain", urn: "urn:ocn:kusama:1005" },
	{ runtimeChain: "Paseo Relay", urn: "urn:ocn:paseo:0" },
	{ runtimeChain: "Paseo Asset Hub", urn: "urn:ocn:paseo:1000" },
];
